//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public hotel()
        {
            this.rooms = new HashSet<room>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string address { get; set; }
        public int stars { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<room> rooms { get; set; }
    }
}
