//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_reservation
    {
        public int id { get; set; }
        public System.DateTime datetime_order { get; set; }
        public Nullable<System.DateTime> datetime_for { get; set; }
        public string status { get; set; }
        public int employee_id { get; set; }
        public int room_id { get; set; }
        public int customer_id { get; set; }
        public int service_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        public virtual room room { get; set; }
        public virtual service service { get; set; }
    }
}
